global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "enviador-promocion"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["enviador-promocion:8080"]

  - job_name: "enviador-productos"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "enviador-productos:8080" ]

  - job_name: "enviador-ventas"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "enviador-ventas:8080" ]

  - job_name: "consultador-mates"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "consultador-mates:8080" ]

  - job_name: "consultador-ventas"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "consultador-ventas:8080" ]
